{
 "title": "Run Store API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "tráfego", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rotas mais usadas",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{uri!~\"/actuator.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "média de requisições por status code",
   "type": "timeseries",
   "description": "quantidade média de requisições agrupadas por status code",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "avg by(status) (http_server_requests_seconds_count{application=\"store-api\", job=\"store-api-pull\", uri!~\"/actuator.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "saturação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "consumo de memória (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(jvm_memory_used_bytes[10s]))by(application) / sum(avg_over_time(jvm_memory_max_bytes[10s]))by(application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "consumo de CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max by(application) (system_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}