services:

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./pg/posgresql.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 25432:5432/tcp

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ./pg/posgresql.env
    environment:
      - SPRING_PROFILES_ACTIVE=pg
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 8080:8080
    logging:
      driver: splunk
      options:
        splunk-url: http://localhost:8088
        splunk-index: logs_storeapp
        splunk-token: 2b8a7c87-713e-48a0-845b-a62e6b7ecb63
        splunk-source: store-api
        splunk-format: "json"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
    depends_on:
      - db
  

volumes:
  pg-data:
    name: postgres-container_pgdata
