server.port: 8080
spring.application.name: store-api
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  metrics:
    tags:
      application: store-api
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          shutdown-operation: POST
          push-rate: PT10S
          job: store-api-push
