server.port: 8080
spring.application.name: store-api

# expondo rotas: /actuator/<health, info, metrics, prometheus>
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo[http.server.requests]: "25ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1500ms"
